export const projects = [
  {
    id: 1,
    title: "Dirlink-Shipping Connector",
    category: "FrontEnd",
    description:
      "A well-designed shipping connector with admin and customer dashboard.",
    images: [
      // "/ProjectsImage/dirlink_logo1.png",
      "/ProjectsImage/dirlink_logo2.png",
      "/ProjectsImage/dirlink_logo3.png",
      "/ProjectsImage/dirlink_logo4.png",
      "/ProjectsImage/dirlink_logo5.png",
      "/ProjectsImage/dirlink_logo6.png",
      "/ProjectsImage/dirlink_logo7.png",
      "/ProjectsImage/dirlink_logo8.png",
      "/ProjectsImage/dirlink_logo9.png",
      "/ProjectsImage/dirlink_logo10.png",
      "/ProjectsImage/dirlink_logo11.png",
      "/ProjectsImage/dirlink_logo12.png",
    ],
    tags: ["React", "Typescript", "Node.js", "Express"],
    siteLink: "https://github.com/yabulala432",
    github: "https://github.com/yabulala432",
  },
  {
    id: 2,
    //
    title: "መዝገበ ስብሐት (Mezgebe Sbhat)",
    category: "Mobile",
    description: "An Ethiopian Orthodox Tewahdo Hymn learning mobile app.",
    video: "/ProjectsImage/mezgebe_sbhat.mp4",
    tags: ["Flutter", "Dart", "Mobile App"],
    sourceLink: "https://github.com/yabulala432/mezgebe_sbhat",
    github: "https://github.com/yabulala432/mezgebe_sbhat",
  },
  {
    id: 3,
    title: "Gamehub Demo",
    category: "FrontEnd",
    description: "A demo platform for game downloads.",
    images: [
      "/ProjectsImage/gamehub1.png",
      "/ProjectsImage/gamehub2.png",
      "/ProjectsImage/gamehub3.png",
      "/ProjectsImage/gamehub4.png",
      "/ProjectsImage/gamehub5.png",
    ],
    tags: ["React", "Typescript", "Gaming"],
    siteLink: "https://game-hub-psi-three.vercel.app/",
    github: "https://github.com/yabulala432/game-hub",
  },
  {
    id: 4,
    title: "መዝገበ ቅዳሴ (Mezgebe Kdase)",
    category: "FrontEnd",
    video: "/ProjectsImage/mezgeb_kdase_web_final.mp4",
    description:
      "A modern Liturgy hymn learning platform for Ethiopian Orthodox Tewahedo Church",
    tags: ["React", "Chakra-UI", "Netlify"],
    siteLink: "https://mezgeb-kdase.netlify.app/",
    github: "https://github.com/yabulala432/zema-web-react/",
  },
  {
    id: 5,
    title: "Pharmacy Management System",
    category: "Backend & FrontEnd",
    images: ["/ProjectsImage/pharmacy1.jpg", "/ProjectsImage/pharmacy2.jpg"],
    description: "Comprehensive solution for managing pharmacy operations",
    tags: ["Java", "MySQL"],
    github: "https://github.com/yabulala432/PharmacyManagementSystemNewUI",
    siteLink: "https://github.com/yabulala432/PharmacyManagementSystemNewUI",
  },
  {
    id: 6,
    category: "FrontEnd, Mobile & Backend",
    images: [
      "/ProjectsImage/bus1.jpg",
      "/ProjectsImage/bus2.jpg",
      "/ProjectsImage/bus3.jpg",
      "/ProjectsImage/bus4.jpg",
      "/ProjectsImage/bus_51.jpg",
      "/ProjectsImage/bus_52.jpg",
      "/ProjectsImage/bus5.jpg",
      "/ProjectsImage/bus6.jpg",
      "/ProjectsImage/operator.jpg",
      "/ProjectsImage/operator1.jpg",
      "/ProjectsImage/operator2.jpg",
      "/ProjectsImage/operator3.jpg",
    ],
    title: "Multi-Tenant Bus-Aggregator Platform",
    description:
      "A complex platform for managing multiple bus companies and their operations",
    tech: [
      "React",
      "Node.js",
      "Express",
      "MongoDB",
      "Docker",
      "Flutter",
      "JWT",
      "Tailwind CSS",
      "TypeScript",
      "Microservices",
    ],
    github: "https://github.com/yabulala432/bus-aggregator-platform",
    demo: "https://github.com/yabulala432/bus-aggregator-platform",
  },
];
